### ISSUE TITLE
Typo in extras.length.m.name.fr

### ISSUE THREAD

**Issue by perki** [pryv/data-types#2]

**Comment by kebetsi** [comment]
Was this fixed? Because it looks fine: https://github.com/pryv/data-types/blob/master/event-extras.json#L1598

**Comment by perki** [comment]
Yes, looks OK

**Comment by kschiess** [comment]
Guys, be definitive. Is this a bug or is it not? Can we close this if not?

**Comment by perki** [comment]
It can be closed
