### ISSUE TITLE
Difference between hierarchical classes' formats and extras classes' formats

### ISSUE THREAD

**Issue by mcamenzind** [pryv/data-types#5]
Some classes are in both Hierarchical and Extras, but not all their formats are in extras.json and hierarchical.json

Example the class mol:
Hierarchical class mol contains 
"formats": {
        "mol": {...},
        "lb-mol": {...}
      }
where extras only contains
"formats": {
        "mol": {
          "name": {...},
          "symbol": "Mol"
        }

Same goes for hierarchical frequency (10 elements) and extras only has 3.
class frequency: in hierarchical, but not in extras:
ghz
khz
megahz
millihz
nhz
thz
uhz

class mol: in hierarchical, but not in extras:
lb-mol

class money: in hierarchical, but not in extras:
aed
bhd
dzd
jod
kes
kwd
mad
mdl
pgk
skk
sll
tnd
tzs
ugx
zmk

**Comment by kschiess** [comment]
Stale issue, closing...
